<a href="https://colab.research.google.com/github/sudeepbhagat11/ML-LAB-102217257/blob/main/ML_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.DataFrame()

df['Name'] = ["abc","xyz","pqr"]
df['Age'] = ["10","20","30"]
df['Gender'] = ["M","F","M"]
df['Address'] = ["abc","acsi", "cdsf"]


df.to_csv('data.csv')
df

  Name Age Gender Address
0  abc  10      M     abc
1  xyz  20      F    acsi
2  pqr  30      M    cdsf

In [2]:
print(df.iloc[0])

Name       abc
Age         10
Gender       M
Address    abc
Name: 0, dtype: object

In [3]:
df.drop('Age',axis=1)

  Name Gender Address
0  abc      M     abc
1  xyz      F    acsi
2  pqr      M    cdsf

In [4]:
df['Age'] = ["10","20",None]
df

  Name   Age Gender Address
0  abc    10      M     abc
1  xyz    20      F    acsi
2  pqr  None      M    cdsf

In [5]:
df.isna()

    Name    Age  Gender  Address
0  False  False   False    False
1  False  False   False    False
2  False   True   False    False

In [6]:
df.dropna().sum()

Name        abcxyz
Age           1020
Gender          MF
Address    abcacsi
dtype: object

In [7]:
df = pd.read_csv('/content/AWCustomers.csv')
df2 = pd.read_csv('/content/AWSales.csv')

In [8]:
df.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [9]:
merged_df = pd.merge(df,df2,on='CustomerID',how='inner')
merged_df.to_csv('merged_file.csv', index=False)
merged_df.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated,BikeBuyer,AvgMonthSpend
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,M,M,1,3,0,1,81916,2017-03-06,1,50.97
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,M,M,1,2,1,2,81076,2017-03-06,1,53.11
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,F,S,0,3,0,0,86387,2017-03-06,1,54.08
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,M,M,1,2,1,2,61481,2017-03-06,1,56.93
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,M,S,1,1,0,0,51804,2017-03-06,1,55.41

In [10]:
merged_df = merged_df.drop(['CustomerID','FirstName','MiddleName','LastName','Suffix','PhoneNumber','Education','MaritalStatus','LastUpdated'],axis=1)

In [11]:
merged_df = merged_df.drop(['AddressLine2'],axis=1)

In [12]:
merged_df = merged_df.drop(['Title'],axis=1)
merged_df.head()

,AddressLine1,City,StateProvinceName,CountryRegionName,PostalCode,BirthDate,Occupation,Gender,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,BikeBuyer,AvgMonthSpend
0,7090 C. Mount Hood,Wollongong,New South Wales,Australia,2500,1987-11-13,Clerical,M,1,3,0,1,81916,1,50.97
1,3651 Willow Lake Rd,Shawnee,British Columbia,Canada,V9B 2C3,1972-07-21,Clerical,M,1,2,1,2,81076,1,53.11
2,1774 Tice Valley Blvd.,West Covina,California,United States,91791,1985-11-09,Clerical,F,0,3,0,0,86387,1,54.08
3,2103 Baldwin Dr,Liverpool,England,United Kingdom,L4 4HB,1977-10-18,Skilled Manual,M,1,2,1,2,61481,1,56.93
4,Am Gallberg 234,Werne,Nordrhein-Westfalen,Germany,59368,1975-02-05,Skilled Manual,M,1,1,0,0,51804,1,55.41

# Handling Null Values

In [13]:
merged_df.isna().sum()

AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
BirthDate               0
Occupation              0
Gender                  0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
BikeBuyer               0
AvgMonthSpend           0
dtype: int64

In [26]:
df_normalize = df["MiddleName"]

In [27]:
df_normalize.head()

0      C
1    NaN
2    NaN
3    NaN
4      J
Name: MiddleName, dtype: object

In [28]:
df_normalize.isna().sum()

7789

In [29]:
df_normalize.fillna(0)

0        C
1        0
2        0
3        0
4        J
        ..
18356    C
18357    0
18358    0
18359    I
18360    0
Name: MiddleName, Length: 18361, dtype: object

In [30]:
df_normalize.fillna(method='ffill')

<ipython-input-30-c2dfa3005245>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_normalize.fillna(method='ffill')

0        C
1        C
2        C
3        C
4        J
        ..
18356    C
18357    C
18358    C
18359    I
18360    I
Name: MiddleName, Length: 18361, dtype: object

In [32]:
df_normalize.fillna(method='bfill')

<ipython-input-32-1208a0a212f6>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_normalize.fillna(method='bfill')

0          C
1          J
2          J
3          J
4          J
        ...
18356      C
18357      I
18358      I
18359      I
18360    NaN
Name: MiddleName, Length: 18361, dtype: object

In [45]:
import numpu
df['TotalChildren'] = df.replace(0,np.nan)

In [48]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df['TotalChildren'] = imputer.fit_transform(df[['TotalChildren']])

In [50]:
df['TotalChildren'].isna().sum()

0

# Normalization

In [64]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['YearlyIncome'] = scaler.fit_transform(df['YearlyIncome'].values.reshape(-1, 1))

In [66]:
df['YearlyIncome'].head()

0    0.496842
1    0.489453
2    0.536172
3    0.317083
4    0.231958
Name: YearlyIncome, dtype: float64

In [67]:
from sklearn.preprocessing import OneHotEncoder
encoder  = OneHotEncoder(sparse=False)
df['Gender'] = encoder.fit_transform(df[['Gender']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [68]:
df['Gender'].head()

0    0.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: Gender, dtype: float64